Algoritmo "20221017-1"
Var
 nA, nB, nC, media : real
 
 funcao med : real
 var aux : real
 inicio
       aux := (nA + nB + nC) / 3
       retorne aux
 fimfuncao
 
Inicio
      escreval("Insira sua nota na P1: ")
      leia(nA)
      escreval("Insira sua nota na P2: ")
      leia(nB)
      escreval("Insira sua nota na P3: ")
      leia(nC)
      
      media := med
      escreva("A média das notas é", media)
Fimalgoritmo